### PR TITLE
impr: updated ul and footer

### PR DESCRIPTION
**Pull request by NipulM**
Made changes to the footer and overall user interface for an improved experience. Furthermore, I have implemented additional optimisations in the code, focusing on improving readability. If there are areas you think can be further improved, please let me know!  🙌🏼

### CODE REVIEW

**Comment by LifeAdventurer** [comment]
Please revert the formatting changes.

**Comment by NipulM** [comment]
I'll revert the formatting changes, but I'm not entirely clear on what you're looking for. Could you provide more details or direct me to the specific formatting preferences in the project?

**Comment by LifeAdventurer** [comment]
You can just adjust the footer part first. I'll try to style all the code in later commits. Is this clear enough?

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
pietroppeter, @dhnanjay, @Rinoahu, @karl-mccarron, @iamnotpi, @harsharamchandra, @Yhmf84white, @industriousrebel, @xinghaow99, @MiracleXYZ, @raniprati, @named-JM, @hossein1387, @eslam69, @aaryadav, @83521166, @off99555, @Sangamesh-ts, @hanq-moreh, @bom-d-van

**Pull request closed without merging**
